
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button botmulti;
	private global::Gtk.Button botsum;
	private global::Gtk.Button botres;
	private global::Gtk.Entry res1;
	private global::Gtk.Entry res2;
	private global::Gtk.Entry resultado;
	private global::Gtk.Label label2;
	private global::Gtk.Label label1;
	private global::Gtk.Label label3;
	private global::Gtk.Button botdiv;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Practica 5");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.botmulti = new global::Gtk.Button ();
		this.botmulti.CanFocus = true;
		this.botmulti.Name = "botmulti";
		this.botmulti.UseUnderline = true;
		this.botmulti.Label = global::Mono.Unix.Catalog.GetString ("Multiplicar");
		this.fixed1.Add (this.botmulti);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.botmulti]));
		w1.X = 219;
		w1.Y = 233;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.botsum = new global::Gtk.Button ();
		this.botsum.CanFocus = true;
		this.botsum.Name = "botsum";
		this.botsum.UseUnderline = true;
		this.botsum.Label = global::Mono.Unix.Catalog.GetString ("Sumar");
		this.fixed1.Add (this.botsum);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.botsum]));
		w2.X = 51;
		w2.Y = 234;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.botres = new global::Gtk.Button ();
		this.botres.CanFocus = true;
		this.botres.Name = "botres";
		this.botres.UseUnderline = true;
		this.botres.Label = global::Mono.Unix.Catalog.GetString ("Restar");
		this.fixed1.Add (this.botres);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.botres]));
		w3.X = 136;
		w3.Y = 234;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.res1 = new global::Gtk.Entry ();
		this.res1.CanFocus = true;
		this.res1.Name = "res1";
		this.res1.IsEditable = true;
		this.res1.InvisibleChar = '●';
		this.fixed1.Add (this.res1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.res1]));
		w4.X = 164;
		w4.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.res2 = new global::Gtk.Entry ();
		this.res2.CanFocus = true;
		this.res2.Name = "res2";
		this.res2.IsEditable = true;
		this.res2.InvisibleChar = '●';
		this.fixed1.Add (this.res2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.res2]));
		w5.X = 163;
		w5.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resultado = new global::Gtk.Entry ();
		this.resultado.CanFocus = true;
		this.resultado.Name = "resultado";
		this.resultado.IsEditable = true;
		this.resultado.InvisibleChar = '●';
		this.fixed1.Add (this.resultado);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resultado]));
		w6.X = 163;
		w6.Y = 143;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w7.X = 69;
		w7.Y = 86;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w8.X = 71;
		w8.Y = 33;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w9.X = 71;
		w9.Y = 147;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.botdiv = new global::Gtk.Button ();
		this.botdiv.CanFocus = true;
		this.botdiv.Name = "botdiv";
		this.botdiv.UseUnderline = true;
		this.botdiv.Label = global::Mono.Unix.Catalog.GetString ("Dividir");
		this.fixed1.Add (this.botdiv);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.botdiv]));
		w10.X = 317;
		w10.Y = 233;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 439;
		this.DefaultHeight = 342;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.botmulti.Clicked += new global::System.EventHandler (this.OnBotmultiClicked);
		this.botsum.Clicked += new global::System.EventHandler (this.OnBotsumClicked);
		this.botres.Clicked += new global::System.EventHandler (this.OnBotresClicked);
		this.botdiv.Clicked += new global::System.EventHandler (this.OnBotdivClicked);
	}
}
